development:
  adapter: postgresql
  encoding: unicode
  database: rhit_development
  host: localhost
  pool: 10

test:
  adapter: postgresql
  encoding: unicode
  database: rhit_test
  host: localhost
  pool: 10
